// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0F3ZU3QPJJIqVxLMMHSMwuR8BAd2jlTQ',
    appId: '1:281626497343:web:b1580b3226b89260f5038a',
    messagingSenderId: '281626497343',
    projectId: 'smartagri1-28afc',
    authDomain: 'smartagri1-28afc.firebaseapp.com',
    storageBucket: 'smartagri1-28afc.appspot.com',
    measurementId: 'G-JYPGVV35VX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUCfFUwmbHSFfBYOOJpKYr84JeaYks09Y',
    appId: '1:281626497343:android:320e366696655836f5038a',
    messagingSenderId: '281626497343',
    projectId: 'smartagri1-28afc',
    storageBucket: 'smartagri1-28afc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkSf-m2kEeVXc4rHenjKE_zaJAaBAcYvo',
    appId: '1:281626497343:ios:3d388a26bbd7ee45f5038a',
    messagingSenderId: '281626497343',
    projectId: 'smartagri1-28afc',
    storageBucket: 'smartagri1-28afc.appspot.com',
    iosClientId: '281626497343-c7l1h6i2ptog5o9k4oesuq42m9qf7a59.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartAgri',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkSf-m2kEeVXc4rHenjKE_zaJAaBAcYvo',
    appId: '1:281626497343:ios:3d388a26bbd7ee45f5038a',
    messagingSenderId: '281626497343',
    projectId: 'smartagri1-28afc',
    storageBucket: 'smartagri1-28afc.appspot.com',
    iosClientId: '281626497343-c7l1h6i2ptog5o9k4oesuq42m9qf7a59.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartAgri',
  );
}
